### ISSUE TITLE
Zones Support

### ISSUE THREAD

**Issue by ruaan-deysel** [nathanvdh/homeassistant-airtouch2#1]
I came across your integration and it's working great so far.

Will zones be added at some point to control individual rooms?

Thanks for your hard work to create this integration.

**Comment by nathanvdh** [comment]
Yes I plan to. I don't have the time at the moment and I'm currently tossing up whether to refactor what I've done to coroutines/await syntax or continue how it is with threads and start on zones.

**Comment by TETZUO** [comment]
Zones would be great. You saved me spending around 1k for an AirTouch 4 and now the AirTouch 5 is about to be released.

**Comment by gogreenpower** [comment]
I currently operate the zones through Assistant Relay, from HA, though Google Assistant to the unit. Its a work around until Nathan has time for zones

**Comment by nathanvdh** [comment]
@gogreenpower @TETZUO @ruaandeysel can you guys test out 0.4.beta1? I just added group/zone control. Seems to work fine for me except you can't currently adjust the %open while the zone is turned off. I think i should be able to fix that though. I'm going away for the weekend tomorrow so wanted to quickly get this done because it was so close.

**Comment by nathanvdh** [comment]
![image](https://user-images.githubusercontent.com/55475809/205044959-fc19c74f-43bf-436a-a0dc-66d5455ff982.png)
They are fan entities, you can add them all into a single card, you need to click on them to show the %open slider.

**Comment by TETZUO** [comment]
> @gogreenpower @TETZUO @ruaandeysel can you guys test out 0.4.beta1? I just added group/zone control. Seems to work fine for me except you can't currently adjust the %open while the zone is turned off. I think i should be able to fix that though. I'm going away for the weekend tomorrow so wanted to quickly get this done because it was so close.

@nathanvdh i have tested this and it works exactly as you describe.

**Comment by TETZUO** [comment]
![0796210F-ACD5-425B-A426-CAA928F14F35](https://user-images.githubusercontent.com/36467084/205050687-886cf3a1-c0b7-4834-a6e9-60d971e05b94.png)

**Comment by gogreenpower** [comment]
Looks like I'm the bad luck. I've made a screen recording, it'll be easier than me trying to explain it. 

Basically toggling in HA toggles two zones in HA but one in the app

https://user-images.githubusercontent.com/9656919/205057099-cc79e323-4a60-42cf-9656-fd6796145df7.mp4

**Comment by gogreenpower** [comment]
Also the fan speed percentages are playing up. HA to the Airtouch unit update sometimes, but the unit to HA don't seem to be updating only on start up

**Comment by nathanvdh** [comment]
> Looks like I'm the bad luck. I've made a screen recording, it'll be easier than me trying to explain it.
> 
> Basically toggling in HA toggles two zones in HA but one in the app
> 
>  Screen_Recording_20221201_204629_Home.Assistant.mp4

Yeah the issue is you have 2 zones/dampers in your first group. I guess I'll have to be a bit more clever with that.

**Comment by nathanvdh** [comment]
@gogreenpower would you be able to send me PCAP dumps of you playing around with your zones? Be sure to include on/off + up/down of the first zone and at least 1 other zone. That would help a lot, thanks.

**Comment by gogreenpower** [comment]
https://1drv.ms/u/s!AhF9jRtLVrOpiKd10ykZ0fmneUWoUw

OneDrive link to PCAP.

IIRC sequence was:
Zone 1 on/off, 100% to 0 and back to 100.
Zone 2 on/off, Z3 on/off, Z4 on/off, Z5 on/off, Z6 on/off.
Then increased the percentage by 10% from zone 2 - 6 and then decreased by 10% 6 - 2

**Comment by nathanvdh** [comment]
I think the commands I'm sending are ok, but I'm reading the response data wrong. The zone info in the message is for each zone/damper, not group. I can see when you adjust the first group's percentage there's 2 zones in the response that get set to the same zone percentage. I'm reading this data as if its groups, not zones. Should be able to fix it pretty easily tomorrow.

**Comment by gogreenpower** [comment]
Yes the first group has 3 outlets and 2 dampeners. The rest should just be singles

**Comment by nathanvdh** [comment]
@gogreenpower Just pushed an update, see how it goes.

**Comment by gogreenpower** [comment]
https://1drv.ms/v/s!AhF9jRtLVrOpiKd6_twboHIuKJL3nQ

Almost

**Comment by nathanvdh** [comment]
> https://1drv.ms/v/s!AhF9jRtLVrOpiKd6_twboHIuKJL3nQ
> 
> Almost

Off by one haha. Gimme a minute

**Comment by nathanvdh** [comment]
> https://1drv.ms/v/s!AhF9jRtLVrOpiKd6_twboHIuKJL3nQ
> 
> Almost

Try the new one. It was just a missed find and replace / typo...doh!

**Comment by gogreenpower** [comment]
Perfect, each group toggles the corresponding entity, both ways, and the % adjustments are all correct as long as the zone is on before adjusting in HA. 

Outstanding work

**Comment by nathanvdh** [comment]
Yes I had a look into it, commanding the zone % while it is off causes strange behavior. I realised you can't even do that with the app or the touchpad so I don't think it's possible.

**Comment by gogreenpower** [comment]
Not that it's a problem but on my system, if the zones are off and I increase the % it turns them on at 10%.

If I decrease to 0% it turns the zone off.

**Comment by nathanvdh** [comment]
> Not that it's a problem but on my system, if the zones are off and I increase the % it turns them on at 10%.
> 
> If I decrease to 0% it turns the zone off.

Yeah same here. Just pushed another update. What I've done now is - if you use the slider and set it 0, it's equivalent to turning off the zone. You can see if you set the slider to zero, and then use the switch to turn the group back on - it should return to to the previous % value. If you drag the slider to a value when the zone is turned off, it will first get turned on and then the % value adjusted to what you specified. Lmk if it works. Then I'll do a few tidy-ups (I'll at least remove 'Group' from the name of the entity) and push a stable release.

**Comment by gogreenpower** [comment]
Yes that works perfectly. updates near instantly

**Comment by nathanvdh** [comment]
Okay I've pushed a stable 0.4 with zone support. I'm using [this custom entity](https://github.com/thomasloven/lovelace-slider-entity-row) to make sliders show on the card so it's a bit more intuitive to use.
