### ISSUE TITLE
Intergration was unable to issue commands to AC after a few weeks of normal operation

### ISSUE THREAD

**Issue by Golli10** [nathanvdh/homeassistant-airtouch2#10]
After a few weeks of normal operation, as unable to control the AC unit from Home Assistant.
I didn't test the fan.x entities (I should've in hindsight!)
Log file attached, of the errors I could find.

Uninstalled the integration and re-setup. It's now working as intended again.

[home-assistant_airtouch2plus_2024-03-09T23-34-52.log](https://github.com/nathanvdh/homeassistant-airtouch2/files/14548166/home-assistant_airtouch2plus_2024-03-09T23-34-52.log)

**Comment by nathanvdh** [comment]
Should be fixed.
