### ISSUE TITLE
Errors found in log file after fresh install (not causing problems with operation)

### ISSUE THREAD

**Issue by Golli10** [nathanvdh/homeassistant-airtouch2#11]
Checked the log file after a fresh install and found the attached error messages.

[home-assistant_airtouch2plus_2024-03-09T23-50-00.log](https://github.com/nathanvdh/homeassistant-airtouch2/files/14548171/home-assistant_airtouch2plus_2024-03-09T23-50-00.log)

**Comment by nathanvdh** [comment]
It's a message that I don't have a spec for, there's at least 2. I've opened a separate issue here: https://github.com/nathanvdh/homeassistant-airtouch2plus/issues/4 but I won't address it myself. Please use the airtouch2**plus** repo in future.
