### ISSUE TITLE
AirTouch integration becomes unavailable 

### ISSUE THREAD

**Issue by randellmatt** [nathanvdh/homeassistant-airtouch2#12]
No sure if others are getting this issue, but my AirTouch integration becomes unavailable almost daily and requires manual reload.

These are the logs from the latest unavailable event.

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:367
integration: Climate (documentation, issues)
First occurred: April 17, 2024 at 7:57:04 PM (7 occurrences)
Last logged: 7:13:47 AM

Entity None (<class 'custom_components.airtouch2plus.Airtouch2PlusClimateEntity.Airtouch2PlusClimateEntity'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/nathanvdh/homeassistant-airtouch2/issues
Entity None (<class 'custom_components.airtouch2plus.Airtouch2PlusClimateEntity.Airtouch2PlusClimateEntity'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/nathanvdh/homeassistant-airtouch2/issues
Entity None (<class 'custom_components.airtouch2plus.Airtouch2PlusClimateEntity.Airtouch2PlusClimateEntity'>) implements HVACMode(s): off, heat_cool, heat, dry, fan_only, cool and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/nathanvdh/homeassistant-airtouch2/issues

**Comment by nathanvdh** [comment]
Could be related to an issue I fixed a little while ago... I only published a beta release though and forgot to make a stable one. Addressed those logs as well. Try the latest 0.7.9 release.

**Comment by randellmatt** [comment]
Sorry Nathan, I think I got lost and posted in the wrong github. This issue is actually for the AirTouch2+ - I currently have 0.2.6 installed. 

I shall reopen this issue for the correct integration.

**Comment by randellmatt** [comment]
Closed and moved to https://github.com/nathanvdh/homeassistant-airtouch2plus/issues/5
