### ISSUE TITLE
Failed to connect to Host IP

### ISSUE THREAD

**Issue by aramshaw** [nathanvdh/homeassistant-airtouch2#15]
I'm unable to connect to the Airtouch2+ device at it's IP address.
![image](https://github.com/nathanvdh/homeassistant-airtouch2/assets/57547910/586dde7e-9b64-4179-92b0-b001a6996d1c)

IP Address per the phone app - so that feels correct
![image](https://github.com/nathanvdh/homeassistant-airtouch2/assets/57547910/699eaa73-4892-424b-ada9-7e47896aaf75)

![image](https://github.com/nathanvdh/homeassistant-airtouch2/assets/57547910/ae9a3471-ebb4-497d-ace7-15d14203f66e)

I can't turn on debugging as I can't get the integration past this first screen.

But here is the only airtouch2 entry in home-assistant.log
2024-05-31 15:10:50.463 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration airtouch2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

Version numbers below.
![image](https://github.com/nathanvdh/homeassistant-airtouch2/assets/57547910/9fec2332-b1df-400b-b136-5011fac5cb8e)

Is there anything else I can provide?

**Comment by nathanvdh** [comment]
You have the Airtouch2 _plus_, this is the wrong integration. Please use https://github.com/nathanvdh/homeassistant-airtouch2plus
