### ISSUE TITLE
Samsung Aircon speed is incorrect

### ISSUE THREAD

**Issue by DmitryNefedov** [nathanvdh/homeassistant-airtouch2#3]
The aircon speed is shown incorrectly in Home Assistant.

Airtouch2 with Samsung, not sure if other manufacturers are affected.

Actual -> HA:
High -> medium
Medium -> low
Low -> diffuse
Auto -> Auto

Happy to provide more info if needed

https://github.com/nathanvdh/homeassistant-airtouch2/blob/22a159c3ce5cba1f130df32822a920d7082b4efd/custom_components/airtouch2/climate.py#L36-L42

**Comment by nathanvdh** [comment]
I assume your aircon does not support 'quiet' mode - there is already an issue open for this. Can you please produce a message dump for me by following these steps: https://github.com/nathanvdh/homeassistant-airtouch2/issues/2#issuecomment-1260845790

**Comment by DmitryNefedov** [comment]
Email sent, cheers!
