### ISSUE TITLE
Config flow could not be loaded: Unknown error

### ISSUE THREAD

**Issue by damian-w** [nathanvdh/homeassistant-airtouch2#4]
Getting a "Config flow could not be loaded: Unknown error" popup when trying to add the integration. Followed all steps, and everything looks okay otherwise. Can't progress any further.

**Comment by nathanvdh** [comment]
> Getting a "Config flow could not be loaded: Unknown error" popup when trying to add the integration. Followed all steps, and everything looks okay otherwise. Can't progress any further.

Are there any airtouch2 warnings logged? (Settings->System->Logs)

**Comment by damian-w** [comment]
Multiple restarts fixed it - couldn't find anything in the log but working now 👍🏻
