### ISSUE TITLE
Multiple units

### ISSUE THREAD

**Issue by scrolls-mckenzie** [nathanvdh/homeassistant-airtouch2#6]
Hello. This is awesome as I couldn't find any other way to do this so thanks for posting. 

Had a question as my setup is a single controller with 2 units. Currently this code operates both of the units. Any thoughts on how to get the second unit working. I'm assuming that the id would ac_1 based on the configuration.yaml

**Comment by scrolls-mckenzie** [comment]
Hello. Just to follow up. there is an error in the logs that might be in relation to this 
`AC0 has an unfamiliar gateway ID: 0x5 - please open an issue and detail your system to me:
	https://github.com/nathanvdh/airtouch2-python/issues/new`
ACO for me would be the main AC unit. The actual controller then has a toggle at the top to select the second unit. This unit then has its own climate settings.
I'm happy to do some debugging on my end if there is a method to poll the unit and get more details about the configuration. Cheers

**Comment by nathanvdh** [comment]
Hey there, you're the first person to try this with 2 units :). Can you please tell me the brand of each unit, e.g. Fujitsu, Dakin, Panasonic etc...

Then, on a computer with Python, install the airtouch2 module with `pip install airtouch2` and the aioconsole module with `pip install aioconsole`. Then can you please run `interactive_test_dumper.py`  [found here](https://github.com/nathanvdh/airtouch2-python/blob/master/test_programs/interactive_test_dumper.py). Just run it with `python3 interactive_test_dumper.py`, enter the IP of the airtouch controller, you should see a bunch of info get printed out about the AC and each group/zone. Just type in `q` at the prompt to quit immediately. It should have created two files, `airtouch2.log` and a `.dump` file. Can you email both of those to me: nathanmvdh@gmail.com.

Finally, can we take further discussion of this over to github.com/nathanvdh/airtouch2-python/issues/4

**Comment by scrolls-mckenzie** [comment]
Sweet. Have moved over to the other repo

**Comment by nathanvdh** [comment]
Done
