### ISSUE TITLE
All entities are gone?

### ISSUE THREAD

**Issue by gogreenpower** [nathanvdh/homeassistant-airtouch2#7]
Hi Nathan,

Just installed your updates and now I have lost all the fan and ac entitites?

![image](https://github.com/nathanvdh/homeassistant-airtouch2/assets/9656919/ad80dab7-e4cd-4908-a213-1f6ed72bdb87)

**Comment by TETZUO** [comment]
Same issue I had to roll back to the public release

**Comment by gogreenpower** [comment]
Roger, trying that now

**Comment by gogreenpower** [comment]
release 0.7 has only the AC unit, no fans, heading back to 0.5beta4

**Comment by gogreenpower** [comment]
Hmmmm, cant get the fans back. Just installed the master version and narda

**Comment by TETZUO** [comment]
> Hmmmm, cant get the fans back. Just installed the master version and narda

You need to delete the integration from the integration menu. 

Then go into HACS and into AirTouch2 click the 3 dots in the upper right then click remove. 

Then search for AirTouch2 again and click download

**Comment by gogreenpower** [comment]
Yeah, done that, even deleted the folder in custom_componets

**Comment by gogreenpower** [comment]
Got it now, master wanted to update to 0.5, done that and I disabled beta version.

**Comment by nathanvdh** [comment]
Oopsie, sorry bout that... I've kind of been abusing the beta feature to test small changes on my own system. There's a much better way to do it so I'll (try very hard to) stop pushing broken updates as betas.

@gogreenpower @TETZUO can you please update to 0.7 stable release I just made and let me know if there's any issues.

**Comment by gogreenpower** [comment]
What changes have been made?

**Comment by nathanvdh** [comment]
Nothing really, it's mostly me doing internal restructuring of the code. I did change the target temperature step size to be correct now though, (it was previously 0.5 but its now whole degrees).

**Comment by gogreenpower** [comment]
Ok, just read the release info as well. Just installed, will let you know if there's any problems. Thanks for the update

**Comment by gogreenpower** [comment]
![Screenshot_20230710_204149_Home Assistant](https://github.com/nathanvdh/homeassistant-airtouch2/assets/9656919/9408969a-ac32-4847-8107-5f6ac3cbd723)
![Screenshot_20230710_204144_Home Assistant](https://github.com/nathanvdh/homeassistant-airtouch2/assets/9656919/b97e397a-b119-434f-af8a-d0a4724f9a9a)

I got a new AC unit which works and the old AC unit becomes unavailable, everything else seems to working

**Comment by nathanvdh** [comment]
Hm alright, I probably changed the unique ID at some point so that's different to the airtouch2+ one. Just delete the old, unavailable entity. Or delete everything and set up the integration again.

**Comment by nathanvdh** [comment]
I'm fairly sure this is resolved. Let me know if that's not the case.
